package com.rbc.zfe0.road.services.transferagent.config;

import org.springframework.beans.factory.annotation.Value;

public class SQLServerSQLs {

    @Value("${schema.name}")
    public static String schemaName = "dzfe0";

    public static String GETSINGLEAGENTSQL = "select * from " + schemaName + ".T_TSFR_AGT where" +
            " ACTV_FLG_IND=1 AND AGT_ID=?";

    public static String DELETEAGENTSQL= "delete * from " + schemaName + ".T_TSFR_AGT where" +
            " ACTV_FLG_IND=?";

    public static String DELETE_TASECURITYLINK= "delete from " + schemaName + ".T_TSFR_AGT_SCTY_LINK where" +
            " DAIN_SCTY_NO=? OR ADP_SCTY_NO=?";

    public static String DELETE_UPDATEACTIVEFLAG_USINGAGTID= "update " + schemaName + ".T_TSFR_AGT set " +
            " ACTV_FLG_IND=0  where AGT_ID=?";

    public static String GETMULTIAGENTSQL = "select * from " + schemaName + ".T_TSFR_AGT where " +
            " ACTV_FLG_IND=1 AND AGT_ID IN (%s)";

    public static String GETALLAGENTSQL = "select * from " + schemaName + ".T_TSFR_AGT WHERE ACTV_FLG_IND =1  ";

    public static String GETAGENTBYNAMESQL = "select * from " + schemaName + ".T_TSFR_AGT WHERE " +
            " ACTV_FLG_IND=1 AND LOWER(AGT_NM) LIKE ?";

    public static String GETALL_INACTIVEAGENTSQL = "select * from " + schemaName + ".T_TSFR_AGT WHERE ACTV_FLG_IND =0 ";


    //AGET NAME is autogenerated
    public static String INSERT_SQL = "INSERT INTO " + schemaName + ".T_TSFR_AGT (\n" +
            "AGT_NM,\n" +
            "ADDR_BOX,\n" +
            "TEL,\n" +
            "FAX,\n" +
            "FEE_AMT,\n" +
            "LST_USED_DT,\n" +
            "LST_UPDT_USR_NM,\n" +
            "LST_UPDT_DT_TM,\n" +
            "ACTV_FLG_IND,\n" +
            //"EMAIL_ID) values (?,?,?,?,?,?,?,?,?,?,?)";
            "EMAIL_ID) values (?,?,?,?,?,?,?,?,?,?)";


    public static String UPDATE_SQL = "UPDATE " + schemaName + ".T_TSFR_AGT " +
            "SET " +
            " AGT_NM = ?," +
            "ADDR_BOX = ?, " +
            "TEL = ?, " +
            "FAX = ?, " +
            "FEE_AMT = ?, " +
            "LST_USED_DT = ?, " +
            "LST_UPDT_USR_NM = ?, " +
            "LST_UPDT_DT_TM = ?, " +
            "EMAIL_ID = ? " +
            " WHERE AGT_ID = ?" ;


    public static String GETTRANSFERITEMFORAGENT = "select count(*) as record_count from " + schemaName + ".T_TSFR_ITM where" +
            " TSFR_AGT_ID=?";

    public static String CHECKAGENTISINACTIVE = "select count(*) as record_count from " + schemaName + ".T_TSFR_AGT where" +
            " AGT_ID=? and ACTV_FLG_IND =1";

    public static String GETTRANSFERAGENTFORSECURITYNUMBER = "select AGT_ID from " + schemaName + ".T_TSFR_AGT_SCTY_LINK where" +
            " DAIN_SCTY_NO =? OR ADP_SCTY_NO =?";




}
